### ISSUE TITLE
[Tests with OC 11] Force encoding profile 'editor.work' was not found and/or EncoderException: Unable to compose an image from track

### ISSUE THREAD

**Issue by mwuttke** [elan-ev/opencast-bigbluebutton-integration#51]
Hello,

We are now testing the opencast-bigbluebutton-integration with Opencast 11. But we had some problems.

Our setup currently in use is right now:
Moodle version: 3.11
OC-Plugin (block + tool) version: both v3.11-r7
Opencast version: 11.7
BigBlueButton version: 2.4.7
opencast-bigbluebutton-integration version: latest master branch

We used for testing purpose the Opencast Integration with BBB plugin for moodle with a patch from Farbod like last year.

The BBB recordings were successfully transferred to opencast but then I've got this error:

```
Error Details

Course: series subject missing - Course_Series_xyz
Instructor: instructor missing
Title: bbb recording test
Event Date: 2022-05-23T10:24:44+02:00

  Workflow failed in operation: 7-partial-import
  Started: 2022-05-23T10:27:45+02:00
  Ended: 2022-05-23T10:27:45+02:00

Logged incident of the error looks like this:

    START_OPERATION org.opencastproject.workflow
org.opencastproject.workflow.api.WorkflowOperationException:
org.opencastproject.workflow.api.WorkflowOperationException: Force encoding profile
'editor.work' was not found
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.start(Partia
lImportWorkflowOperationHandler.java:178)
at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:193
)
at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:1
16)
at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.j
ava:803)
at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1851)
at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:22
90)
at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:22
56)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.opencastproject.workflow.api.WorkflowOperationException: Force encoding
profile 'editor.work' was not found
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler$1.apply(Part
ialImportWorkflowOperationHandler.java:610)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler$1.apply(Part
ialImportWorkflowOperationHandler.java:604)
at com.entwinemedia.fn.data.Opt.fmap(Opt.java:94)
at com.entwinemedia.fn.data.Opt.map(Opt.java:99)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.getForceEnco
dingProfile(PartialImportWorkflowOperationHandler.java:604)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.concat(Parti
alImportWorkflowOperationHandler.java:207)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.start(Partia
lImportWorkflowOperationHandler.java:176)
... 10 more

```

After I added the [encoding profile for opencast-videos](https://github.com/opencast/opencast/blob/10.13/etc/encoding/opencast-movies.properties) from version 10.13 I've got the following error:

```
Course: series subject missing - Course_Series_xyz
Instructor: instructor missing
Title: bbb recording test 005
Event Date: 2022-05-23T12:35:28+02:00

  Workflow failed in operation: 7-partial-import
  Started: 2022-05-23T12:38:44+02:00
  Ended: 2022-05-23T12:39:22+02:00

Logged incident of the error looks like this:

    org.opencastproject.util.NotFoundException
at org.opencastproject.workspace.impl.WorkspaceImpl.downloadIfNecessary(WorkspaceImpl.java:517)
at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:539)
at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:536)
at org.opencastproject.util.data.Function$X.apply(Function.java:104)
at org.opencastproject.util.IoSupport.locked(IoSupport.java:478)
at org.opencastproject.workspace.impl.WorkspaceImpl.get(WorkspaceImpl.java:384)
at org.opencastproject.composer.impl.ComposerServiceImpl.loadTrackIntoWorkspace(ComposerServiceImpl
.java:320)
at org.opencastproject.composer.impl.ComposerServiceImpl.concat(ComposerServiceImpl.java:926)
at org.opencastproject.composer.impl.ComposerServiceImpl.process(ComposerServiceImpl.java:1512)
at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313)
at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

    START_OPERATION org.opencastproject.workflow
org.opencastproject.workflow.api.WorkflowOperationException:
org.opencastproject.composer.api.EncoderException: Unable to compose an image from track
https://mydomoain.com/files/collection/composer/103866_slide1_[..] using the
remote composer service proxy
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.start(Partia
lImportWorkflowOperationHandler.java:178)
at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:193
)
at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:1
16)
at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.j
ava:803)
at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1851)
at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:22
90)
at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:22
56)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.opencastproject.composer.api.EncoderException: Unable to compose an image
from track https://mydomoain.com/files/collection/composer/103866_slide1_[..]
using the remote composer service proxy
at org.opencastproject.composer.remote.ComposerServiceRemoteImpl.image(ComposerServiceRemoteImpl.ja
va:297)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.extractImage
(PartialImportWorkflowOperationHandler.java:1034)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.processChild
ren(PartialImportWorkflowOperationHandler.java:945)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.concat(Parti
alImportWorkflowOperationHandler.java:287)
at org.opencastproject.workflow.handler.composer.PartialImportWorkflowOperationHandler.start(Partia
lImportWorkflowOperationHandler.java:176)
... 10 more
```
Is there anything missing in the opencast config?

Thanks & with regards,
Michael

**Comment by Arnei** [comment]
You probably want to add the profile `encode.partial-import` to your encodings, as specified here: https://docs.opencast.org/r/11.x/admin/#workflowoperationhandlers/partial-import-woh/#missing-encoding-profiles. And change your workflow to use it instead of `editor.work`.

Opencast 11 had some clean-up performed on its workflows and encoding profiles, I suppose that is why there is no more `editor.work` encoding profile in Opencast 11. Additionally, some of the encoding profiles used by the "Partial Import" workflow operation are also not included in Opencast 11, but have to be added manually (there are examples in the docs that should work). We should probably update our post-archive ReadMe and bbb-upload-*.xml example workflow to reflect that.

**Comment by mwuttke** [comment]
Hello Arne, thanks for the hints. I added the missing-encodung.profiles and ajusted the bbb-upload.xml workflow as you recommended it. But on our production system with opencast 11.6 we ran into the following error:

```
Error Details

Course: series subject missing - Course_Series_xyz
Instructor: instructor missing
Title: BBB Test with Opencast 11.6
Event Date: 2022-05-24T09:49:47+02:00

  Workflow failed in operation: 30-image
  Started: 2022-05-24T09:56:39+02:00
  Ended: 2022-05-24T09:56:45+02:00

Logged incident of the error looks like this:

    Image org.opencastproject.composer
org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation
'Image'
at org.opencastproject.composer.impl.ComposerServiceImpl.process(ComposerServiceImpl.java:1545)
at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313)
at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.opencastproject.composer.api.EncoderException: Extracted image
/srv/opencast/workspace/mediapackage/26971975-59cd-493c-8787-6ee5a50bb2fb/3dec71b3-e34d-4db3-8a6e-1f
787e412168/slide1-7e8b58db-3a78-4c76-8a2a-d1d3f9d64cb9_df4d5f30-efa4-4402-8bd3-74008b5d8532-search.jp
g
is empty!
at org.opencastproject.composer.impl.ComposerServiceImpl.extractImages(ComposerServiceImpl.java:120
3)
at org.opencastproject.composer.impl.ComposerServiceImpl.process(ComposerServiceImpl.java:1437)
... 6 more
```
This error does not occur on the test system with opencast 11.7. The config is mor or less the same. ;-(

**Comment by mwuttke** [comment]
The BBB OC integration test with Opencast 11.7 works as expected. I will close this issue. Thanks!

BTW: An update of the post-archive ReadMe and bbb-upload-*.xml example workflow would be helpfull. ;-)
